<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/06/11 12:55:09

$database = new sfPropelDatabase();
$database->initialize(array (
  'dsn' => 'mysql://root:admin@localhost/chirichat',
), 'propel');
$this->databases['propel'] = $database;
